package main.java.features;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;


import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import com.sun.scenario.effect.ImageData;
import javafx.collections.ObservableList;
import javafx.scene.control.Cell;
import main.java.dao.PackageTypeDAO;
import main.java.dao.PackagesDAO;
import main.java.entity.PackagesDTO;
import main.java.entity.PdfAreaDTO;
import main.java.entity.PdfDTO;

public class PdfGenerator {
    private static String FILE = "D:/sample.pdf";

    private static Font catFont = new Font(Font.FontFamily.HELVETICA, 18,
            Font.BOLD);
    private static Font smallFont = new Font(Font.FontFamily.HELVETICA, 12,
            Font.NORMAL);
    private static Font subFont = new Font(Font.FontFamily.HELVETICA, 16,
            Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.HELVETICA, 12,
            Font.BOLD);

    public static void createPdf(Date start, Date end) throws IOException, DocumentException {
        File file = new File(FILE);
        file.getParentFile().mkdirs();
        new PdfGenerator().fillPdf(FILE, start, end);
    }

    public void fillPdf(String dest, Date start, Date end) throws IOException, DocumentException {
        Font font = new Font(Font.FontFamily.HELVETICA, 13, Font.BOLD, GrayColor.GRAYWHITE);
        BaseFont baseFont = BaseFont.createFont(BaseFont.HELVETICA, BaseFont.CP1250, BaseFont.CACHED);
        Font tableFont = new Font(baseFont);

        Document document = new Document(PageSize.A4.rotate());
        PdfWriter.getInstance(document, new FileOutputStream(dest));
        document.open();

        PdfPTable mainTable = new PdfPTable(2);
        mainTable.setWidthPercentage(100);

        Image image = Image.getInstance("src/main/resources/images/outbox_black.png");
        image.scaleAbsolute(100, 100);

        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Date now = new Date();

        LocalDate localEnd = Instant.ofEpochMilli(end.getTime()).atZone(ZoneId.systemDefault()).toLocalDate();

        Paragraph paragraph = new Paragraph(
                "Report generated by: Admin" + "\n" + simpleDateFormat.format(now)
                        + "\n" + "Date from: " + start + " Date to: " + localEnd.minusDays(1),tableFont);



        PdfPCell cell = new PdfPCell(image);
        cell.setBorder(Rectangle.NO_BORDER);
        PdfPCell cell2 = new PdfPCell(paragraph);
        cell2.setBorder(Rectangle.NO_BORDER);
        cell2.setHorizontalAlignment(Element.ALIGN_RIGHT);
        cell2.setVerticalAlignment(Element.ALIGN_MIDDLE);


        paragraph.setAlignment(Paragraph.ALIGN_BOTTOM);
        mainTable.addCell(cell);
        mainTable.addCell(cell2);
        document.add(mainTable);



        Paragraph empty = new Paragraph();
        addEmptyLine(empty, 1);
        document.add(empty);


        Paragraph data = new Paragraph("Data", subFont);
        document.add(data);

        ObservableList<PdfDTO> packList = PackagesDAO.readPackagesForPdf(start, end);

        int smallCounter = 0;
        int midCounter = 0;
        int bigCounter = 0;
        for(int i = 0; i < packList.size(); i++) {
            if (packList.get(i).getSize().equals("mała") ) {
                smallCounter++;

            }
            if (packList.get(i).getSize().equals("średnia")) {
                midCounter++;
            }
            if (packList.get(i).getSize().equals("duża")) {
                bigCounter++;
            }
        }

        Double smallPrice = Double.valueOf(PackageTypeDAO.getPackageTypes().get(0).getPrice());
        Double midPrice = Double.valueOf(PackageTypeDAO.getPackageTypes().get(1).getPrice());
        Double bigPrice = Double.valueOf(PackageTypeDAO.getPackageTypes().get(2).getPrice());

        Double packValue = smallCounter*smallPrice + midCounter*midPrice + bigCounter*bigPrice;

        Paragraph value = new Paragraph("Value of packages: " + packValue + " zł", tableFont);
        document.add(value);

        Paragraph number = new Paragraph("Number of packages:", smallBold);
        document.add(number);

        Paragraph small = new Paragraph("Small - " + smallCounter, smallFont);
        document.add(small);

        Paragraph medium = new Paragraph("Medium - " + midCounter, smallFont);
        document.add(medium);

        Paragraph big = new Paragraph("Big - " + bigCounter, smallFont);
        document.add(big);


        addEmptyLine(empty, 2);
        document.add(empty);


        float[] columnAreaWidths = {1, 5, 5, 5, 5, 5};
        PdfPTable tableArea = new PdfPTable(columnAreaWidths);
        tableArea.setWidthPercentage(100);
        tableArea.getDefaultCell().setUseAscender(true);
        tableArea.getDefaultCell().setUseDescender(true);


        tableArea.addCell(createCell("#", font));
        tableArea.addCell(createCell("Area Name", font));
        tableArea.addCell(createCell("Number of small", font));
        tableArea.addCell(createCell("Number of medium", font));
        tableArea.addCell(createCell("Number of big", font));
        tableArea.addCell(createCell("Value of packages", font));
        tableArea.getDefaultCell().setBackgroundColor(new GrayColor(0.75f));



        tableArea.setHeaderRows(1);
        List<PdfAreaDTO> listArea = PackageTypeDAO.readAreasForPdf(start, end);


        for (int i = 0; i < listArea.size(); i++) {

            if (listArea.get(i).getSmallPackages() == 0 && listArea.get(i).getMediumPackages() == 0 &&
                    listArea.get(i).getBigPackages() == 0) {

                listArea.remove(i);
                i--;
            }
        }

        tableArea.getDefaultCell().setHorizontalAlignment(Element.ALIGN_CENTER);
        for (int counter = 0; counter < listArea.size(); counter++) {
            if (counter % 2 == 1){
                tableArea.getDefaultCell().setBackgroundColor(GrayColor.GRAYWHITE);
            }else{
                tableArea.getDefaultCell().setBackgroundColor(GrayColor.LIGHT_GRAY);
            }
            tableArea.addCell(String.valueOf(counter + 1));
            tableArea.addCell(new Phrase(listArea.get(counter).getAreaName(), tableFont));
            tableArea.addCell(new Phrase(String.valueOf(listArea.get(counter).getSmallPackages()), tableFont));
            tableArea.addCell(new Phrase(String.valueOf(listArea.get(counter).getMediumPackages()), tableFont));
            tableArea.addCell(new Phrase(String.valueOf(listArea.get(counter).getBigPackages()), tableFont));
            tableArea.addCell(new Phrase(String.valueOf(listArea.get(counter).getSmallPackages() * smallPrice +
                    listArea.get(counter).getMediumPackages() * midPrice +
                    listArea.get(counter).getBigPackages() * bigPrice), tableFont));

        }
        document.add(tableArea);


        addEmptyLine(empty, 2);
        document.add(empty);

        float[] columnWidths = {1, 5, 5, 5, 5, 5};
        PdfPTable table = new PdfPTable(columnWidths);
        table.setWidthPercentage(100);
        table.getDefaultCell().setUseAscender(true);
        table.getDefaultCell().setUseDescender(true);


        table.addCell(createCell("#", font));
        table.addCell(createCell("Package number", font));
        table.addCell(createCell("Size", font));
        table.addCell(createCell("City", font));
        table.addCell(createCell("Voivodeship", font));
        table.addCell(createCell("Date", font));
        table.getDefaultCell().setBackgroundColor(new GrayColor(0.75f));



        table.setHeaderRows(1);
        ObservableList<PdfDTO> list = PackagesDAO.readPackagesForPdf(start, end);
        table.getDefaultCell().setHorizontalAlignment(Element.ALIGN_CENTER);
        for (int counter = 0; counter < list.size(); counter++) {
            if (counter % 2 == 1){
                table.getDefaultCell().setBackgroundColor(GrayColor.GRAYWHITE);
            }else{
                table.getDefaultCell().setBackgroundColor(GrayColor.LIGHT_GRAY);
            }
            table.addCell(String.valueOf(counter + 1));
            table.addCell(new Phrase(list.get(counter).getPackageNumber(), tableFont));
            table.addCell(new Phrase(list.get(counter).getSize(), tableFont));
            table.addCell(new Phrase(list.get(counter).getCity(), tableFont));
            table.addCell(new Phrase(list.get(counter).getVoivodeship(), tableFont));
            table.addCell(new Phrase(simpleDateFormat.format(list.get(counter).getDate()), tableFont));

        }
        document.add(table);
        document.close();
    }

    private PdfPCell createCell(String text, Font font){
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setBackgroundColor(GrayColor.GRAYBLACK);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        return cell;
    }

    private static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }
}